import type { TranslationShape } from "../../en/app/app";
import type enAuth from "../../en/auth/auth";
const auth = {
  login: { close: "Cerrar inicio de sesión", eyebrow: "Te damos la bienvenida", title: "Iniciar sesión", email: "Correo electrónico", emailPlaceholder: "tu@email.com", password: "Contraseña", passwordPlaceholder: "contraseña", submit: "Iniciar sesión", or: "o", noAccount: "¿Aún no tienes una cuenta?", register: "Regístrate ahora" },
  register: { close: "Cerrar registro", eyebrow: "Únete a Flypnp", title: "Registrarse", name: "Nombre completo", namePlaceholder: "Juan Pérez", email: "Correo electrónico", emailPlaceholder: "tu@email.com", password: "Contraseña", photo: "Foto de perfil", submit: "Registrarse", or: "o", member: "¿Ya tienes una cuenta?", login: "Iniciar sesión" },
  forgot: { title: "Olvidé mi contraseña", emailPlaceholder: "Introduce tu correo", submit: "Enviar correo" },
  update: { eyebrow: "Datos personales", title: "Actualizar perfil", closeEditor: "Cerrar editor de perfil", displayName: "Nombre visible", namePlaceholder: "Editar nombre", password: "Nueva contraseña", passwordPlaceholder: "Déjalo vacío para mantener la actual", hint: "Solo se actualizarán los campos que completes.", close: "Cerrar", submit: "Actualizar" },
  profile: { journal: "Diario de viaje", welcome: "Te damos la bienvenida, {{name}}", title: "Tu próxima historia comienza aquí.", description: "Mantén juntos tus lugares favoritos, próximas aventuras y recuerdos de viaje.", mountainAlt: "Viaje por montañas nevadas", avatarAlt: "Avatar de {{name}}", changePicture: "Cambiar foto de perfil", guestType: "Huésped curioso · Explorador", verified: "Correo verificado", saved: "Guardados", reviews: "Reseñas", trips: "Viajes", edit: "Editar perfil", logout: "Cerrar sesión", wishlist: "Favoritos", savedPlaces: "Lugares guardados", upcomingStays: "Próximas estancias", bookings: "Reservas", travelHistory: "Historial de viajes", inspiration: "Tu inspiración", collections: "Colecciones de lugares", viewAll: "Ver todo", topPick: "Selección destacada", favorite: "Lugar favorito", favoriteDescription: "Un lugar al que merece la pena volver, guardado para tu próxima escapada.", exploreStay: "Explorar alojamiento", location: "Zúrich, Suiza", about: "Un poco sobre mí", bio: "Siempre buscando mañanas tranquilas en la montaña, espacios cuidados y la mejor comida local.", achievements: "Logros", localTime: "Hora local", socialLabel: "Perfil social {{number}}", editDialog: "Editar perfil" },
} satisfies TranslationShape<typeof enAuth>;
export default auth;
