import type { TranslationShape } from "../../en/app/app"; import type enSearch from "../../en/search/search";
const search = {
  search: "Buscar", searchStays: "Buscar alojamientos", searchExperiences: "Buscar experiencias", where: "Dónde", searchDestinations: "Buscar destinos", addDates: "Añadir fechas", checkIn: "Llegada", checkOut: "Salida", date: "Fecha", chooseDates: "Elegir fechas", chooseDatesTitle: "Elige tus fechas", chooseDatesDescription: "Selecciona primero la llegada y después la salida", closeDates: "Cerrar selector de fechas", previousMonth: "Mes anterior", nextMonth: "Mes siguiente", flexible: "Flexible", months: "Meses", exactDays:"Días exactos",day_one:"día",day_other:"días",
  guests: { label: "Huéspedes", add: "Añadir huéspedes", open: "Abrir selector de huéspedes", dialog: "Elegir huéspedes", title: "¿Quién viene?", description: "Forma tu grupo de viaje", selected: "{{count}} viajeros seleccionados", adults: "Adultos", adultsDescription: "13 años o más", children: "Niños", childrenDescription: "De 2 a 12 años", infants: "Bebés", infantsDescription: "Menores de 2 años", pets: "Mascotas", petsDescription: "¿Traes un amigo peludo?", decrease: "Reducir {{label}}", increase: "Aumentar {{label}}", count: "Cantidad de {{label}}" },
  destination: { explore: "Explorar destinos", backRegions: "Volver a las regiones", eyebrow: "¿Cuál es tu próximo destino?", exploreRegion: "Explorar {{region}}", chooseRegion: "Elige una región", exitFullMap: "Salir del mapa a pantalla completa", openFullMap: "Abrir mapa a pantalla completa", exitFull: "Salir de pantalla completa", full: "Pantalla completa", close: "Cerrar explorador de destinos", quick: "Destinos rápidos", matching: "Coincidencias con «{{destination}}»", suggestions: "Destinos sugeridos", noMatch: "No hay coincidencias directas. Elige una región para explorar el mapa.", searchIn: "Buscar en {{region}}", searchCountry: "Buscar país en {{region}}", selectCountry: "Selecciona un país", noCountry: "No se encontró ningún país en esta región.", loadingMap: "Cargando mapa interactivo…", clear: "Borrar destino", interactiveMap: "Mapa interactivo de {{place}}", chooseCountryHint: "Elige un país para ver alojamientos", noStays: "Aún no hay alojamientos de muestra", removed: "Eliminado de tus favoritos", saved: "Guardado en tus favoritos", signIn: "Inicia sesión para guardar este alojamiento", removeWishlist: "Eliminar {{title}} de favoritos", saveWishlist: "Guardar {{title}} en favoritos", night: "noche" },
  destinationExtra: { useCountry: "Usar {{country}}", mapRepresenting: "Mapa de {{region}}", showPlace: "Mostrar {{title}}, CHF {{price}} por noche", simulated: "{{count}} alojamientos · {{simulated}} simulados", verified: "{{count}} alojamientos con ubicación verificada", searchByRegion: "Buscar por región", flexible: "Soy flexible" },
  regionCards:{africa:{name:"África",eyebrow:"Desiertos, costas y safaris"},americas:{name:"América",eyebrow:"Ciudades, islas y naturaleza salvaje"},asia:{name:"Asia",eyebrow:"Templos, megaciudades e islas"},europe:{name:"Europa",eyebrow:"Estancias alpinas y ciudades históricas"},oceania:{name:"Oceanía",eyebrow:"Escapadas al océano y horizontes abiertos"}},
  validation: { chooseBothDates: "Elige las fechas de llegada y salida.", checkoutAfter: "La salida debe ser posterior a la llegada." },
  summary: { guest_one: "{{count}} huésped", guest_other: "{{count}} huéspedes", infant_one: "{{count}} bebé", infant_other: "{{count}} bebés", pet_one: "{{count}} mascota", pet_other: "{{count}} mascotas" },
  regions: { southeastAsia: "Sudeste asiático", germany: "Alemania", unitedStates: "Estados Unidos", italy: "Italia", africa: "África" },
} satisfies TranslationShape<typeof enSearch>; export default search;
