import type { TranslationShape } from "../../en/app/app";
import type enAuth from "../../en/auth/auth";
const auth = {
  login: { close: "Fermer la connexion", eyebrow: "Bon retour", title: "Se connecter", email: "Adresse e-mail", emailPlaceholder: "vous@email.com", password: "Mot de passe", passwordPlaceholder: "mot de passe", submit: "Se connecter", or: "ou", noAccount: "Vous n’avez pas encore de compte ?", register: "S’inscrire maintenant" },
  register: { close: "Fermer l’inscription", eyebrow: "Rejoignez Flypnp", title: "S’inscrire", name: "Nom complet", namePlaceholder: "Jean Dupont", email: "Adresse e-mail", emailPlaceholder: "vous@email.com", password: "Mot de passe", photo: "Photo de profil", submit: "S’inscrire", or: "ou", member: "Déjà membre ?", login: "Se connecter" },
  forgot: { title: "Mot de passe oublié", emailPlaceholder: "Saisissez votre e-mail", submit: "Envoyer l’e-mail" },
  update: { eyebrow: "Informations personnelles", title: "Mettre à jour le profil", closeEditor: "Fermer l’éditeur de profil", displayName: "Nom affiché", namePlaceholder: "Modifier le nom", password: "Nouveau mot de passe", passwordPlaceholder: "Laissez vide pour conserver l’actuel", hint: "Seuls les champs renseignés seront mis à jour.", close: "Fermer", submit: "Mettre à jour" },
  profile: { journal: "Carnet de voyage", welcome: "Bon retour, {{name}}", title: "Votre prochaine histoire commence ici.", description: "Réunissez vos escapades favorites, vos prochaines aventures et vos souvenirs de voyage.", mountainAlt: "Voyage dans les montagnes enneigées", avatarAlt: "Avatar de {{name}}", changePicture: "Changer la photo de profil", guestType: "Voyageur curieux · Explorateur", verified: "E-mail vérifié", saved: "Enregistrés", reviews: "Avis", trips: "Voyages", edit: "Modifier le profil", logout: "Se déconnecter", wishlist: "Favoris", savedPlaces: "Lieux enregistrés", upcomingStays: "Séjours à venir", bookings: "Réservations", travelHistory: "Historique des voyages", inspiration: "Votre inspiration", collections: "Collections de lieux", viewAll: "Tout voir", topPick: "Coup de cœur", favorite: "Lieu préféré", favoriteDescription: "Un lieu où revenir, enregistré pour votre prochaine escapade.", exploreStay: "Explorer le séjour", location: "Zurich, Suisse", about: "À propos de moi", bio: "Toujours à la recherche de matins paisibles en montagne, de lieux soignés et des meilleures saveurs locales.", achievements: "Réussites", localTime: "Heure locale", socialLabel: "Profil social {{number}}", editDialog: "Modifier le profil" },
} satisfies TranslationShape<typeof enAuth>;
export default auth;
