import type { TranslationShape } from "../../en/app/app"; import type enSearch from "../../en/search/search";
const search = {
  search: "Suchen", searchStays: "Unterkünfte suchen", searchExperiences: "Erlebnisse suchen", where: "Wohin", searchDestinations: "Reiseziele suchen", addDates: "Daten hinzufügen", checkIn: "Check-in", checkOut: "Check-out", date: "Datum", chooseDates: "Daten auswählen", chooseDatesTitle: "Wähle deine Daten", chooseDatesDescription: "Wähle zuerst den Check-in und dann den Check-out", closeDates: "Datumsauswahl schließen", previousMonth: "Vorheriger Monat", nextMonth: "Nächster Monat", flexible: "Flexibel", months: "Monate", exactDays:"Genaue Tage",day_one:"Tag",day_other:"Tage",
  guests: { label: "Gäste", add: "Gäste hinzufügen", open: "Gästeauswahl öffnen", dialog: "Gäste auswählen", title: "Wer kommt mit?", description: "Stelle deine Reisegruppe zusammen", selected: "{{count}} Reisende ausgewählt", adults: "Erwachsene", adultsDescription: "Ab 13 Jahren", children: "Kinder", childrenDescription: "2–12 Jahre", infants: "Kleinkinder", infantsDescription: "Unter 2 Jahren", pets: "Haustiere", petsDescription: "Kommt ein Vierbeiner mit?", decrease: "{{label}} verringern", increase: "{{label}} erhöhen", count: "Anzahl {{label}}" },
  destination: { explore: "Reiseziele entdecken", backRegions: "Zurück zu den Regionen", eyebrow: "Wohin als Nächstes?", exploreRegion: "{{region}} entdecken", chooseRegion: "Region auswählen", exitFullMap: "Vollbildkarte verlassen", openFullMap: "Karte im Vollbild öffnen", exitFull: "Vollbild verlassen", full: "Vollbild", close: "Reisezielsuche schließen", quick: "Schnelle Reiseziele", matching: "Treffer für „{{destination}}“", suggestions: "Vorgeschlagene Reiseziele", noMatch: "Kein direkter Treffer. Wähle eine Region, um die Karte zu erkunden.", searchIn: "In {{region}} suchen", searchCountry: "Land in {{region}} suchen", selectCountry: "Land auswählen", noCountry: "In dieser Region wurde kein Land gefunden.", loadingMap: "Interaktive Karte wird geladen…", clear: "Reiseziel löschen", interactiveMap: "Interaktive Karte von {{place}}", chooseCountryHint: "Wähle ein Land, um Unterkünfte zu sehen", noStays: "Noch keine Beispielunterkünfte verfügbar", removed: "Aus den Favoriten entfernt", saved: "In den Favoriten gespeichert", signIn: "Melde dich an, um diese Unterkunft zu speichern", removeWishlist: "{{title}} aus Favoriten entfernen", saveWishlist: "{{title}} in Favoriten speichern", night: "Nacht" },
  destinationExtra: { useCountry: "{{country}} verwenden", mapRepresenting: "Karte von {{region}}", showPlace: "{{title}} anzeigen, CHF {{price}} pro Nacht", simulated: "{{count}} Unterkünfte · {{simulated}} simuliert", verified: "{{count}} Unterkünfte an bestätigten Standorten", searchByRegion: "Nach Region suchen", flexible: "Ich bin flexibel" },
  regionCards:{africa:{name:"Afrika",eyebrow:"Wüsten, Küsten & Safaris"},americas:{name:"Amerika",eyebrow:"Städte, Inseln & wilde Natur"},asia:{name:"Asien",eyebrow:"Tempel, Megastädte & Inseln"},europe:{name:"Europa",eyebrow:"Alpenaufenthalte & historische Städte"},oceania:{name:"Ozeanien",eyebrow:"Auszeiten am Meer & weite Horizonte"}},
  validation: { chooseBothDates: "Wähle Check-in- und Check-out-Datum.", checkoutAfter: "Der Check-out muss nach dem Check-in liegen." },
  summary: { guest_one: "{{count}} Gast", guest_other: "{{count}} Gäste", infant_one: "{{count}} Kleinkind", infant_other: "{{count}} Kleinkinder", pet_one: "{{count}} Haustier", pet_other: "{{count}} Haustiere" },
  regions: { southeastAsia: "Südostasien", germany: "Deutschland", unitedStates: "Vereinigte Staaten", italy: "Italien", africa: "Afrika" },
} satisfies TranslationShape<typeof enSearch>; export default search;
