import type { TranslationShape } from "../../en/app/app"; import type enSearch from "../../en/search/search";
const search = {
  search: "Cerca", searchStays: "Cerca soggiorni", searchExperiences: "Cerca esperienze", where: "Dove", searchDestinations: "Cerca destinazioni", addDates: "Aggiungi date", checkIn: "Check-in", checkOut: "Check-out", date: "Data", chooseDates: "Scegli le date", chooseDatesTitle: "Scegli le tue date", chooseDatesDescription: "Seleziona prima il check-in, poi il check-out", closeDates: "Chiudi selettore date", previousMonth: "Mese precedente", nextMonth: "Mese successivo", flexible: "Flessibile", months: "Mesi", exactDays:"Giorni esatti",day_one:"giorno",day_other:"giorni",
  guests: { label: "Ospiti", add: "Aggiungi ospiti", open: "Apri selettore ospiti", dialog: "Scegli gli ospiti", title: "Chi viene?", description: "Crea il tuo gruppo di viaggio", selected: "{{count}} viaggiatori selezionati", adults: "Adulti", adultsDescription: "13 anni o più", children: "Bambini", childrenDescription: "2–12 anni", infants: "Neonati", infantsDescription: "Meno di 2 anni", pets: "Animali", petsDescription: "Porti un amico a quattro zampe?", decrease: "Riduci {{label}}", increase: "Aumenta {{label}}", count: "Numero di {{label}}" },
  destination: { explore: "Esplora destinazioni", backRegions: "Torna alle regioni", eyebrow: "Dove si va?", exploreRegion: "Esplora {{region}}", chooseRegion: "Scegli una regione", exitFullMap: "Esci dalla mappa a schermo intero", openFullMap: "Apri la mappa a schermo intero", exitFull: "Esci da schermo intero", full: "Schermo intero", close: "Chiudi esplorazione destinazioni", quick: "Destinazioni rapide", matching: "Risultati per “{{destination}}”", suggestions: "Destinazioni suggerite", noMatch: "Nessuna corrispondenza diretta. Scegli una regione per esplorare la mappa.", searchIn: "Cerca in {{region}}", searchCountry: "Cerca paese in {{region}}", selectCountry: "Seleziona un paese", noCountry: "Nessun paese trovato in questa regione.", loadingMap: "Caricamento mappa interattiva…", clear: "Cancella destinazione", interactiveMap: "Mappa interattiva di {{place}}", chooseCountryHint: "Scegli un paese per vedere i soggiorni", noStays: "Nessun soggiorno di esempio disponibile", removed: "Rimosso dai preferiti", saved: "Salvato nei preferiti", signIn: "Accedi per salvare questo soggiorno", removeWishlist: "Rimuovi {{title}} dai preferiti", saveWishlist: "Salva {{title}} nei preferiti", night: "notte" },
  destinationExtra: { useCountry: "Usa {{country}}", mapRepresenting: "Mappa di {{region}}", showPlace: "Mostra {{title}}, CHF {{price}} a notte", simulated: "{{count}} soggiorni · {{simulated}} simulati", verified: "{{count}} soggiorni in posizioni verificate", searchByRegion: "Cerca per regione", flexible: "Sono flessibile" },
  regionCards:{africa:{name:"Africa",eyebrow:"Deserti, coste e safari"},americas:{name:"Americhe",eyebrow:"Città, isole e natura selvaggia"},asia:{name:"Asia",eyebrow:"Templi, metropoli e isole"},europe:{name:"Europa",eyebrow:"Soggiorni alpini e città storiche"},oceania:{name:"Oceania",eyebrow:"Fughe sull'oceano e orizzonti aperti"}},
  validation: { chooseBothDates: "Scegli le date di check-in e check-out.", checkoutAfter: "Il check-out deve essere successivo al check-in." },
  summary: { guest_one: "{{count}} ospite", guest_other: "{{count}} ospiti", infant_one: "{{count}} neonato", infant_other: "{{count}} neonati", pet_one: "{{count}} animale", pet_other: "{{count}} animali" },
  regions: { southeastAsia: "Sud-est asiatico", germany: "Germania", unitedStates: "Stati Uniti", italy: "Italia", africa: "Africa" },
} satisfies TranslationShape<typeof enSearch>; export default search;
