import type { AppTranslations } from "../../en/app/app";

const app = {
  common: { flypnpHome: "Inicio de Flypnp", close: "Cerrar", tryAgain: "Intentar de nuevo", loading: "Cargando…", reserve: "Reservar", create: "Crear", clear: "Borrar" },
  home: { eyebrow: "Encuentra tu próximo alojamiento", title: "Alójate en un lugar que se sienta como una historia digna de contar.", description: "Alojamientos únicos, reservas sencillas y escapadas inolvidables, todo en un solo lugar." },
  footer: { description: "Alojamientos memorables y experiencias locales para viajeros que quieren sentirse como en casa en cualquier lugar.", madeIn: "Hecho con cariño en Suiza", explore: "Explorar", stays: "Alojamientos", experiences: "Experiencias", services: "Servicios", wishlist: "Favoritos", trips: "Viajes", profile: "Mi perfil", giftCards: "Tarjetas regalo", help: "Centro de ayuda", contact: "Contáctanos", rights: "Todos los derechos reservados.", tagline: "Viaja con la mente abierta" },
  welcome: { close: "Cerrar bienvenida", eyebrow: "Tu viaje comienza aquí", title: "Te damos la bienvenida a Flypnp", titleWithName: "¡Hola, {{name}}!", returningDescription: "Nos alegra tenerte aquí. Tu próxima estancia inolvidable está lista para ser descubierta.", newDescription: "Descubre alojamientos únicos, destinos inspiradores y nuevas historias por todo el mundo.", progress: "La experiencia principal está lista; solo falta un 25 % para el lanzamiento final.", start: "Empezar a explorar" },
  access: { checking: "Comprobando tu sesión", checkingProgress: "Comprobando tu sesión…" },
  notifications: { deleted: "Notificación eliminada correctamente.", deleteError: "No se pudo eliminar la notificación.", inbox: "Bandeja de entrada", empty: "Aún no tienes notificaciones", title: "Tus notificaciones", defaultTitle: "Novedad de Flypnp", unread: "Sin leer", viewDetails: "Ver detalles", markRead: "Marcar como leída", delete: "Eliminar notificación" },
  wishlist: { deleted: "Alojamiento eliminado correctamente", eyebrow: "Guardado para después", title: "Lugares en los que no puedes dejar de pensar.", description: "Ten cerca cada alojamiento inspirador y convierte un favorito en tu próxima aventura.", savedPlaces_one: "Lugar guardado", savedPlaces_other: "Lugares guardados", collection: "Tu colección", myWishlist: "Mis favoritos", discoverMore: "Descubrir más", loading: "Cargando favoritos", loadErrorTitle: "No pudimos cargar tus favoritos", loadErrorDescription: "Tus lugares guardados siguen seguros. Inténtalo de nuevo.", emptyTitle: "Tus favoritos están listos para inspirarte", emptyDescription: "Pulsa el corazón de cualquier alojamiento que te guste y lo encontrarás aquí.", explore: "Explorar alojamientos", removeLabel: "Eliminar {{title}} de favoritos", savedExperience: "Experiencia guardada", savedStay: "Alojamiento guardado", ready: "Cuando tú quieras", reserve: "Reservar", dialogLabel: "Eliminar lugar guardado", closeDialog: "Cerrar diálogo de eliminación", removeTitle: "¿Eliminar de favoritos?", removeNamed: "{{title}} dejará de aparecer en tus lugares guardados.", removeGeneric: "Este alojamiento dejará de aparecer en tu colección.", keep: "Conservar", remove: "Eliminar lugar", created: "¡Lista de favoritos creada correctamente!", saveError: "No se pudo guardar este elemento ({{itemType}}). Inicia sesión e inténtalo de nuevo.", closeCreate: "Cerrar diálogo de favoritos", createTitle: "Crear lista de favoritos", namePlaceholder: "Ponle un nombre", characters: "caracteres", overLimit: "Has superado el límite de caracteres.", clear: "Borrar", create: "Crear" },
  stubs: { notFound: "Página no encontrada", booking: "Reserva", accountNav: "Navegación de la cuenta", editProfile: "Editar perfil", places: "Alojamientos", rooms: "Habitaciones", update: "Actualizar" },
} satisfies AppTranslations;

export default app;
