const search = {
  search: "Search", searchStays: "Search stays", searchExperiences: "Search experiences", where: "Where", searchDestinations: "Search destinations", addDates: "Add dates", checkIn: "Check in", checkOut: "Check out", date: "Date", chooseDates: "Choose dates", chooseDatesTitle: "Choose your dates", chooseDatesDescription: "Select check-in first, then check-out", closeDates: "Close date picker", previousMonth: "Previous month", nextMonth: "Next month", flexible: "Flexible", months: "Months", exactDays:"Exact days",day_one:"day",day_other:"days",
  guests: { label: "Guests", add: "Add guests", open: "Open guest selector", dialog: "Choose guests", title: "Who’s coming?", description: "Build your travel crew", selected: "{{count}} travelers selected", adults: "Adults", adultsDescription: "Age 13 or above", children: "Children", childrenDescription: "Ages 2–12", infants: "Infants", infantsDescription: "Under 2", pets: "Pets", petsDescription: "Bringing a furry friend?", decrease: "Decrease {{label}}", increase: "Increase {{label}}", count: "{{label}} count" },
  destination: { explore: "Explore destinations", backRegions: "Back to regions", eyebrow: "Where next?", exploreRegion: "Explore {{region}}", chooseRegion: "Choose a region", exitFullMap: "Exit full screen map", openFullMap: "Open map in full screen", exitFull: "Exit full screen", full: "Full screen", close: "Close destination explorer", quick: "Quick destinations", matching: "Matching “{{destination}}”", suggestions: "Suggested destinations", noMatch: "No direct match. Choose a region to explore the map.", searchIn: "Search in {{region}}", searchCountry: "Search country in {{region}}", selectCountry: "Select a country", noCountry: "No country found in this region.", loadingMap: "Loading interactive map…", clear: "Clear destination", interactiveMap: "Interactive map of {{place}}", chooseCountryHint: "Choose a country to see stays", noStays: "No sample stays available yet", removed: "Removed from your wishlist", saved: "Saved to your wishlist", signIn: "Sign in to save this stay to your wishlist", removeWishlist: "Remove {{title}} from wishlist", saveWishlist: "Save {{title}} to wishlist", night: "night" },
  destinationExtra: { useCountry: "Use {{country}}", mapRepresenting: "Map representing {{region}}", showPlace: "Show {{title}}, CHF {{price}} per night", simulated: "{{count}} stays · {{simulated}} simulated", verified: "{{count}} stays at verified locations", searchByRegion: "Search by region", flexible: "I'm flexible" },
  regionCards:{africa:{name:"Africa",eyebrow:"Deserts, coasts & safaris"},americas:{name:"Americas",eyebrow:"Cities, islands & wild nature"},asia:{name:"Asia",eyebrow:"Temples, megacities & islands"},europe:{name:"Europe",eyebrow:"Alpine stays & old-world cities"},oceania:{name:"Oceania",eyebrow:"Ocean escapes & open horizons"}},
  validation: { chooseBothDates: "Choose both check-in and check-out dates.", checkoutAfter: "Check-out must be after check-in." },
  summary: { guest_one: "{{count}} guest", guest_other: "{{count}} guests", infant_one: "{{count}} infant", infant_other: "{{count}} infants", pet_one: "{{count}} pet", pet_other: "{{count}} pets" },
  regions: { southeastAsia: "Southeast Asia", germany: "Germany", unitedStates: "United States", italy: "Italy", africa: "Africa" },
} as const;
export default search;
