import type { AppTranslations } from "../../en/app/app";

const app = {
  common: { flypnpHome: "Home di Flypnp", close: "Chiudi", tryAgain: "Riprova", loading: "Caricamento…", reserve: "Prenota", create: "Crea", clear: "Cancella" },
  home: { eyebrow: "Trova il tuo prossimo soggiorno", title: "Soggiorna in un luogo che sembra una storia da raccontare.", description: "Alloggi unici, prenotazioni semplici e fughe memorabili, tutto in un unico posto." },
  footer: { description: "Soggiorni memorabili ed esperienze locali per chi vuole sentirsi a casa ovunque.", madeIn: "Creato con cura in Svizzera", explore: "Esplora", stays: "Soggiorni", experiences: "Esperienze", services: "Servizi", wishlist: "Preferiti", trips: "Viaggi", profile: "Il mio profilo", giftCards: "Carte regalo", help: "Centro assistenza", contact: "Contattaci", rights: "Tutti i diritti riservati.", tagline: "Viaggia con una mente aperta" },
  welcome: { close: "Chiudi la finestra di benvenuto", eyebrow: "Il tuo viaggio inizia qui", title: "Benvenuto su Flypnp", titleWithName: "Benvenuto, {{name}}!", returningDescription: "È bello averti qui. Il tuo prossimo soggiorno indimenticabile è pronto per essere scoperto.", newDescription: "Scopri soggiorni unici, destinazioni stimolanti e nuove storie in tutto il mondo.", progress: "L’esperienza principale è pronta: manca solo il 25% alla versione finale.", start: "Inizia a esplorare" },
  access: { checking: "Verifica della sessione", checkingProgress: "Verifica della sessione…" },
  notifications: { deleted: "Notifica eliminata.", deleteError: "Impossibile eliminare la notifica.", inbox: "Posta in arrivo", empty: "Nessuna notifica", title: "Le tue notifiche", defaultTitle: "Aggiornamento Flypnp", unread: "Da leggere", viewDetails: "Vedi dettagli", markRead: "Segna come letta", delete: "Elimina notifica" },
  wishlist: { deleted: "Alloggio eliminato correttamente", eyebrow: "Salvato per dopo", title: "Luoghi a cui non riesci a smettere di pensare.", description: "Tieni vicini i soggiorni che ti ispirano e trasforma un preferito nella tua prossima avventura.", savedPlaces_one: "Luogo salvato", savedPlaces_other: "Luoghi salvati", collection: "La tua raccolta", myWishlist: "I miei preferiti", discoverMore: "Scopri di più", loading: "Caricamento preferiti", loadErrorTitle: "Impossibile caricare i preferiti", loadErrorDescription: "I luoghi salvati sono al sicuro. Riprova.", emptyTitle: "I tuoi preferiti sono pronti a ispirarti", emptyDescription: "Tocca il cuore su un soggiorno che ami e lo ritroverai qui.", explore: "Esplora i soggiorni", removeLabel: "Rimuovi {{title}} dai preferiti", savedExperience: "Esperienza salvata", savedStay: "Soggiorno salvato", ready: "Quando vuoi", reserve: "Prenota", dialogLabel: "Rimuovi luogo salvato", closeDialog: "Chiudi la finestra di rimozione", removeTitle: "Rimuovere dai preferiti?", removeNamed: "{{title}} non apparirà più nei luoghi salvati.", removeGeneric: "Questo alloggio non apparirà più nella raccolta.", keep: "Mantieni", remove: "Rimuovi luogo", created: "Lista dei preferiti creata!", saveError: "Impossibile salvare questo elemento ({{itemType}}). Accedi e riprova.", closeCreate: "Chiudi la finestra dei preferiti", createTitle: "Crea una lista di preferiti", namePlaceholder: "Dai un nome alla lista", characters: "caratteri", overLimit: "Limite di caratteri superato.", clear: "Cancella", create: "Crea" },
  stubs: { notFound: "Pagina non trovata", booking: "Prenotazione", accountNav: "Navigazione account", editProfile: "Modifica profilo", places: "Alloggi", rooms: "Camere", update: "Aggiorna" },
} satisfies AppTranslations;

export default app;
