import type { AppTranslations } from "../../en/app/app";

const app = {
  common: { flypnpHome: "Accueil Flypnp", close: "Fermer", tryAgain: "Réessayer", loading: "Chargement…", reserve: "Réserver", create: "Créer", clear: "Effacer" },
  home: { eyebrow: "Trouvez votre prochain séjour", title: "Séjournez dans un lieu qui ressemble à une histoire qui mérite d’être racontée.", description: "Des logements uniques, une réservation simple et des escapades mémorables, réunis au même endroit." },
  footer: { description: "Des séjours mémorables et des expériences locales pour les voyageurs qui veulent se sentir chez eux partout.", madeIn: "Créé avec soin en Suisse", explore: "Explorer", stays: "Séjours", experiences: "Expériences", services: "Services", wishlist: "Favoris", trips: "Voyages", profile: "Mon profil", giftCards: "Cartes cadeaux", help: "Centre d’aide", contact: "Nous contacter", rights: "Tous droits réservés.", tagline: "Voyagez l’esprit ouvert" },
  welcome: { close: "Fermer la fenêtre de bienvenue", eyebrow: "Votre voyage commence ici", title: "Bienvenue sur Flypnp", titleWithName: "Bienvenue, {{name}} !", returningDescription: "Nous sommes ravis de vous accueillir. Votre prochain séjour inoubliable n’attend que vous.", newDescription: "Découvrez des séjours uniques, des destinations inspirantes et de nouvelles histoires à travers le monde.", progress: "L’expérience principale est prête — plus que 25 % avant la version finale.", start: "Commencer à explorer" },
  access: { checking: "Vérification de votre session", checkingProgress: "Vérification de votre session…" },
  notifications: { deleted: "Notification supprimée.", deleteError: "La notification n’a pas pu être supprimée.", inbox: "Boîte de réception", empty: "Aucune notification pour le moment", title: "Vos notifications", defaultTitle: "Actualité Flypnp", unread: "Non lue", viewDetails: "Voir les détails", markRead: "Marquer comme lue", delete: "Supprimer la notification" },
  wishlist: { deleted: "Logement supprimé avec succès", eyebrow: "Enregistré pour plus tard", title: "Ces lieux auxquels vous ne cessez de penser.", description: "Gardez vos séjours préférés à portée de main et transformez un favori en prochaine aventure.", savedPlaces_one: "Lieu enregistré", savedPlaces_other: "Lieux enregistrés", collection: "Votre collection", myWishlist: "Mes favoris", discoverMore: "En découvrir plus", loading: "Chargement des favoris", loadErrorTitle: "Impossible de charger vos favoris", loadErrorDescription: "Vos lieux enregistrés sont toujours en sécurité. Réessayez.", emptyTitle: "Vos favoris sont prêts à vous inspirer", emptyDescription: "Touchez le cœur d’un séjour qui vous plaît pour le retrouver ici.", explore: "Explorer les séjours", removeLabel: "Retirer {{title}} des favoris", savedExperience: "Expérience enregistrée", savedStay: "Séjour enregistré", ready: "Quand vous voulez", reserve: "Réserver", dialogLabel: "Retirer le lieu enregistré", closeDialog: "Fermer la fenêtre de suppression", removeTitle: "Retirer des favoris ?", removeNamed: "{{title}} ne figurera plus dans vos lieux enregistrés.", removeGeneric: "Ce logement ne figurera plus dans votre collection.", keep: "Conserver", remove: "Retirer le lieu", created: "Liste de favoris créée !", saveError: "Impossible d’enregistrer cet élément ({{itemType}}). Connectez-vous et réessayez.", closeCreate: "Fermer la fenêtre des favoris", createTitle: "Créer une liste de favoris", namePlaceholder: "Nommez votre liste", characters: "caractères", overLimit: "Limite de caractères dépassée.", clear: "Effacer", create: "Créer" },
  stubs: { notFound: "Page introuvable", booking: "Réservation", accountNav: "Navigation du compte", editProfile: "Modifier le profil", places: "Logements", rooms: "Chambres", update: "Mettre à jour" },
} satisfies AppTranslations;

export default app;
