const auth = {
  login: { close: "Close login dialog", eyebrow: "Welcome back", title: "Login", email: "Email address", emailPlaceholder: "your@email.com", password: "Password", passwordPlaceholder: "password", submit: "Login", or: "or", noAccount: "Don't have an account yet?", register: "Register now" },
  register: { close: "Close register dialog", eyebrow: "Join Flypnp", title: "Register", name: "Full name", namePlaceholder: "John Doe", email: "Email address", emailPlaceholder: "your@email.com", password: "Password", photo: "Profile photo", submit: "Register", or: "or", member: "Already a member?", login: "Login" },
  forgot: { title: "Forgot Password", emailPlaceholder: "Enter your email", submit: "Send Email" },
  update: { eyebrow: "Personal details", title: "Update profile", closeEditor: "Close profile editor", displayName: "Display name", namePlaceholder: "Edit name", password: "New password", passwordPlaceholder: "Leave blank to keep current", hint: "Only the fields you complete will be updated.", close: "Close", submit: "Update" },
  profile: { journal: "Travel journal", welcome: "Welcome back, {{name}}", title: "Your next story starts here.", description: "Keep your favorite escapes, upcoming adventures and travel memories together.", mountainAlt: "Snowy mountain journey", avatarAlt: "{{name}}'s avatar", changePicture: "Change profile picture", guestType: "Curious guest · Explorer", verified: "Verified email", saved: "Saved", reviews: "Reviews", trips: "Trips", edit: "Edit profile", logout: "Logout", wishlist: "Wishlist", savedPlaces: "Saved places", upcomingStays: "Upcoming stays", bookings: "Bookings", travelHistory: "Travel history", inspiration: "Your inspiration", collections: "Place collections", viewAll: "View all", topPick: "Top pick", favorite: "Favorite place", favoriteDescription: "A place worth returning to, saved for your next escape.", exploreStay: "Explore stay", location: "Zurich, Switzerland", about: "A little about me", bio: "Always looking for quiet mountain mornings, thoughtful spaces and the best local food.", achievements: "Achievements", localTime: "Local time", socialLabel: "Social profile {{number}}", editDialog: "Edit profile" },
} as const;

export default auth;
