import type { TranslationShape } from "../../en/app/app";
import type enAuth from "../../en/auth/auth";
const auth = {
  login: { close: "Chiudi accesso", eyebrow: "Bentornato", title: "Accedi", email: "Indirizzo email", emailPlaceholder: "tu@email.com", password: "Password", passwordPlaceholder: "password", submit: "Accedi", or: "oppure", noAccount: "Non hai ancora un account?", register: "Registrati ora" },
  register: { close: "Chiudi registrazione", eyebrow: "Unisciti a Flypnp", title: "Registrati", name: "Nome completo", namePlaceholder: "Mario Rossi", email: "Indirizzo email", emailPlaceholder: "tu@email.com", password: "Password", photo: "Foto profilo", submit: "Registrati", or: "oppure", member: "Hai già un account?", login: "Accedi" },
  forgot: { title: "Password dimenticata", emailPlaceholder: "Inserisci la tua email", submit: "Invia email" },
  update: { eyebrow: "Dati personali", title: "Aggiorna profilo", closeEditor: "Chiudi editor profilo", displayName: "Nome visualizzato", namePlaceholder: "Modifica nome", password: "Nuova password", passwordPlaceholder: "Lascia vuoto per mantenere quella attuale", hint: "Verranno aggiornati solo i campi compilati.", close: "Chiudi", submit: "Aggiorna" },
  profile: { journal: "Diario di viaggio", welcome: "Bentornato, {{name}}", title: "La tua prossima storia inizia qui.", description: "Tieni insieme fughe preferite, prossime avventure e ricordi di viaggio.", mountainAlt: "Viaggio tra montagne innevate", avatarAlt: "Avatar di {{name}}", changePicture: "Cambia foto profilo", guestType: "Ospite curioso · Esploratore", verified: "Email verificata", saved: "Salvati", reviews: "Recensioni", trips: "Viaggi", edit: "Modifica profilo", logout: "Esci", wishlist: "Preferiti", savedPlaces: "Luoghi salvati", upcomingStays: "Soggiorni futuri", bookings: "Prenotazioni", travelHistory: "Cronologia viaggi", inspiration: "La tua ispirazione", collections: "Raccolte di luoghi", viewAll: "Vedi tutto", topPick: "Scelta migliore", favorite: "Luogo preferito", favoriteDescription: "Un luogo in cui tornare, salvato per la prossima fuga.", exploreStay: "Esplora soggiorno", location: "Zurigo, Svizzera", about: "Qualcosa su di me", bio: "Sempre alla ricerca di tranquille mattine in montagna, spazi curati e il miglior cibo locale.", achievements: "Traguardi", localTime: "Ora locale", socialLabel: "Profilo social {{number}}", editDialog: "Modifica profilo" },
} satisfies TranslationShape<typeof enAuth>;
export default auth;
