import type { TranslationShape } from "../../en/app/app"; import type enSearch from "../../en/search/search";
const search = {
  search: "Rechercher", searchStays: "Rechercher des séjours", searchExperiences: "Rechercher des expériences", where: "Où", searchDestinations: "Rechercher une destination", addDates: "Ajouter des dates", checkIn: "Arrivée", checkOut: "Départ", date: "Date", chooseDates: "Choisir les dates", chooseDatesTitle: "Choisissez vos dates", chooseDatesDescription: "Sélectionnez d’abord l’arrivée, puis le départ", closeDates: "Fermer le sélecteur de dates", previousMonth: "Mois précédent", nextMonth: "Mois suivant", flexible: "Flexible", months: "Mois", exactDays:"Dates exactes",day_one:"jour",day_other:"jours",
  guests: { label: "Voyageurs", add: "Ajouter des voyageurs", open: "Ouvrir le sélecteur de voyageurs", dialog: "Choisir les voyageurs", title: "Qui vient ?", description: "Composez votre groupe de voyage", selected: "{{count}} voyageurs sélectionnés", adults: "Adultes", adultsDescription: "13 ans ou plus", children: "Enfants", childrenDescription: "2 à 12 ans", infants: "Bébés", infantsDescription: "Moins de 2 ans", pets: "Animaux", petsDescription: "Vous voyagez avec un compagnon ?", decrease: "Diminuer {{label}}", increase: "Augmenter {{label}}", count: "Nombre de {{label}}" },
  destination: { explore: "Explorer les destinations", backRegions: "Retour aux régions", eyebrow: "Où partir ensuite ?", exploreRegion: "Explorer {{region}}", chooseRegion: "Choisissez une région", exitFullMap: "Quitter la carte en plein écran", openFullMap: "Ouvrir la carte en plein écran", exitFull: "Quitter le plein écran", full: "Plein écran", close: "Fermer l’explorateur de destinations", quick: "Destinations rapides", matching: "Résultats pour « {{destination}} »", suggestions: "Destinations suggérées", noMatch: "Aucun résultat direct. Choisissez une région pour explorer la carte.", searchIn: "Rechercher dans {{region}}", searchCountry: "Rechercher un pays dans {{region}}", selectCountry: "Sélectionnez un pays", noCountry: "Aucun pays trouvé dans cette région.", loadingMap: "Chargement de la carte interactive…", clear: "Effacer la destination", interactiveMap: "Carte interactive de {{place}}", chooseCountryHint: "Choisissez un pays pour voir les séjours", noStays: "Aucun exemple de séjour pour le moment", removed: "Retiré de vos favoris", saved: "Ajouté à vos favoris", signIn: "Connectez-vous pour enregistrer ce séjour", removeWishlist: "Retirer {{title}} des favoris", saveWishlist: "Ajouter {{title}} aux favoris", night: "nuit" },
  destinationExtra: { useCountry: "Choisir {{country}}", mapRepresenting: "Carte représentant {{region}}", showPlace: "Afficher {{title}}, CHF {{price}} par nuit", simulated: "{{count}} séjours · {{simulated}} simulés", verified: "{{count}} séjours avec emplacement vérifié", searchByRegion: "Rechercher par région", flexible: "Je suis flexible" },
  regionCards:{africa:{name:"Afrique",eyebrow:"Déserts, côtes et safaris"},americas:{name:"Amériques",eyebrow:"Villes, îles et nature sauvage"},asia:{name:"Asie",eyebrow:"Temples, mégapoles et îles"},europe:{name:"Europe",eyebrow:"Séjours alpins et villes historiques"},oceania:{name:"Océanie",eyebrow:"Escapades océanes et grands horizons"}},
  validation: { chooseBothDates: "Choisissez les dates d’arrivée et de départ.", checkoutAfter: "Le départ doit être postérieur à l’arrivée." },
  summary: { guest_one: "{{count}} voyageur", guest_other: "{{count}} voyageurs", infant_one: "{{count}} bébé", infant_other: "{{count}} bébés", pet_one: "{{count}} animal", pet_other: "{{count}} animaux" },
  regions: { southeastAsia: "Asie du Sud-Est", germany: "Allemagne", unitedStates: "États-Unis", italy: "Italie", africa: "Afrique" },
} satisfies TranslationShape<typeof enSearch>; export default search;
