import type { TranslationShape } from "../../en/app/app";
import type enAuth from "../../en/auth/auth";
const auth = {
  login: { close: "Anmeldedialog schließen", eyebrow: "Willkommen zurück", title: "Anmelden", email: "E-Mail-Adresse", emailPlaceholder: "du@email.com", password: "Passwort", passwordPlaceholder: "Passwort", submit: "Anmelden", or: "oder", noAccount: "Noch kein Konto?", register: "Jetzt registrieren" },
  register: { close: "Registrierung schließen", eyebrow: "Werde Teil von Flypnp", title: "Registrieren", name: "Vollständiger Name", namePlaceholder: "Max Mustermann", email: "E-Mail-Adresse", emailPlaceholder: "du@email.com", password: "Passwort", photo: "Profilfoto", submit: "Registrieren", or: "oder", member: "Bereits registriert?", login: "Anmelden" },
  forgot: { title: "Passwort vergessen", emailPlaceholder: "E-Mail eingeben", submit: "E-Mail senden" },
  update: { eyebrow: "Persönliche Angaben", title: "Profil aktualisieren", closeEditor: "Profileditor schließen", displayName: "Anzeigename", namePlaceholder: "Name bearbeiten", password: "Neues Passwort", passwordPlaceholder: "Leer lassen, um das aktuelle zu behalten", hint: "Nur ausgefüllte Felder werden aktualisiert.", close: "Schließen", submit: "Aktualisieren" },
  profile: { journal: "Reisetagebuch", welcome: "Willkommen zurück, {{name}}", title: "Deine nächste Geschichte beginnt hier.", description: "Bewahre Lieblingsauszeiten, kommende Abenteuer und Reiseerinnerungen an einem Ort auf.", mountainAlt: "Reise durch verschneite Berge", avatarAlt: "Avatar von {{name}}", changePicture: "Profilbild ändern", guestType: "Neugieriger Gast · Entdecker", verified: "E-Mail bestätigt", saved: "Gespeichert", reviews: "Bewertungen", trips: "Reisen", edit: "Profil bearbeiten", logout: "Abmelden", wishlist: "Favoriten", savedPlaces: "Gespeicherte Orte", upcomingStays: "Kommende Aufenthalte", bookings: "Buchungen", travelHistory: "Reiseverlauf", inspiration: "Deine Inspiration", collections: "Orte-Sammlungen", viewAll: "Alle ansehen", topPick: "Top-Auswahl", favorite: "Lieblingsort", favoriteDescription: "Ein Ort zum Wiederkommen, gespeichert für deine nächste Auszeit.", exploreStay: "Unterkunft entdecken", location: "Zürich, Schweiz", about: "Ein wenig über mich", bio: "Immer auf der Suche nach ruhigen Bergmorgen, durchdachten Räumen und dem besten lokalen Essen.", achievements: "Erfolge", localTime: "Ortszeit", socialLabel: "Social-Profil {{number}}", editDialog: "Profil bearbeiten" },
} satisfies TranslationShape<typeof enAuth>;
export default auth;
