const places = {
  card: { view: "View {{title}}", save: "Save {{title}} to wishlist", night: "night" },
  gallery: { explore: "Explore", loading: "Loading...", loadingStays:"Loading stays",loadTitle:"We couldn’t load the stays",loadText:"Check that the backend is running and try again.",tryAgain:"Try again",emptyTitle:"No stays found here yet",emptyText:"Try another category or clear your destination search.",showPhotos:"Show all {{count}} photos", categories: { trending: "Trending", beachfront: "Beachfront", iconicCities: "Iconic cities", tinyHomes: "Tiny homes", mansions: "Mansions", cabins: "Cabins", skiing: "Skiing", design: "Design", tropical: "Tropical", castles: "Castles", surfing: "Surfing", caves: "Caves", camping: "Camping", luxe: "Luxe" } },
  details: {
    loading: "Loading place", loadTitle: "We couldn't load this stay", loadText: "Please check your connection and try again.", tryAgain: "Try again", notFound: "Place not found", unavailable: "This stay may no longer be available.",
    shareText: "Check out {{title}} on Flypnp!", linkCopied: "Link copied to clipboard!", removed: "Removed from wishlist", reviews: "reviews", sharePlace: "Share this place", share: "Share", twitter: "X (Twitter)", copyLink: "Copy link", removeWishlist: "Remove from wishlist", savePlace: "Save this place", saved: "Saved", save: "Save", reserve: "Reserve", reserveDialog:"Reserve this place", viewPhoto: "{{title}} view {{number}}", guestFavorite: "Guest favorite", about: "About this stay", loved: "Loved by travelers", favoriteTitle: "A Flypnp guest favorite", favoriteText: "One of the most loved homes, according to guests who keep coming back.", hostAlt: "Host Jane", hostedBy: "Hosted by Jane", hostMeta: "Superhost · 4 years hosting", close: "Close reservation", closeOverlay:"Close reservation overlay",
    highlights: {
      room: { title: "Room in a chalet", text: "Your own room in the home, plus access to shared spaces." },
      common: { title: "Shared common spaces", text: "You'll share part of the home with the host and other guests." },
      bathroom: { title: "Shared bathroom", text: "You'll share a bathroom with the host and other guests in the home." },
      superhost: { title: "Jane is a Superhost", text: "An experienced, highly rated host committed to memorable stays." }
    }
  },
  reservation: {
    remove: "Remove {{label}}", add: "Add {{label}}", addDate: "Add date", loading: "Loading reservation", fallbackError: "Could not start your reservation", signIn: "Log in to reserve this place.", chooseDates: "Choose valid check-in and check-out dates.", addAdult: "Add at least one adult.", tooMany: "This place allows up to {{count}} guests.",
    guests_one: "{{count}} guest", guests_other: "{{count}} guests", infants_one: "{{count}} infant", infants_other: "{{count}} infants", pets_one: "{{count}} pet", pets_other: "{{count}} pets", addGuests: "Add guests", night: "night", checkIn: "Check-in", checkOut: "Check-out", guestsLabel: "Guests", adults: "Adults", adultNote: "Age 13 or above", children: "Children", childNote: "Ages 2–12", infants: "Infants", infantNote: "Under 2", pets: "Pets", petNote: "Service animals are always welcome", done: "Done", starting: "Starting reservation…", reserve: "Reserve", noCharge: "You won't be charged yet", nights_one: "{{price}} CHF × {{count}} night", nights_other: "{{price}} CHF × {{count}} nights", selectDates: "Select dates", serviceFee: "Flypnp service fee", total: "Total before taxes", protected: "Your booking is protected by Flypnp guest support.", closeOverlay: "Close calendar overlay", closeCalendar: "Close calendar"
  },
  form: {
    loadError: "Could not load this listing", locateError: "We could not locate this address", photosUploaded: "Photos uploaded", uploadError: "Could not upload these photos", photoAdded: "Photo added", addImageError: "Could not add this image", loginError: "Log in before creating a listing.", photoRequired: "Add at least one photo.", updated: "Listing updated", created: "Your home is now listed", saveError: "Could not save this listing", loginTitle: "Log in to list your home", loginText: "Use the user menu to log in before creating or editing a property.", back: "Back to Flypnp", loading: "Loading listing…", dashboard: "Host dashboard", editEyebrow: "Edit your place", createEyebrow: "Create a listing", editTitle: "Keep your listing fresh.", createTitle: "Tell travelers about your home.", title: "Listing title", titlePlaceholder: "Quiet alpine apartment", address: "Address", addressPlaceholder: "Street, city and country", locateHint: "We’ll locate it automatically when you leave this field.", locating: "Locating this address…", located: "Address located", tryAgain: "Try again", category: "Category", trending: "Trending", beachfront: "Beachfront", iconicCity: "Iconic city", price: "Nightly price (CHF)", maxGuests: "Maximum guests", perks: "Perks", perksPlaceholder: "Wi-Fi, kitchen, parking", perksHint: "Separate each perk with a comma.", description: "Description", descriptionPlaceholder: "What makes this place memorable?", extra: "House rules and extra information", extraPlaceholder: "Check-in instructions, quiet hours and anything guests should know.", photos: "Photos", photosHint: "Add at least one clear image.", urlPlaceholder: "Paste a public image URL", addLink: "Add link", upload: "Upload", uploading: "Uploading photos…", removePhoto: "Remove photo {{number}}", saving: "Saving…", locatingAddress: "Locating address…", saveChanges: "Save changes", publish: "Publish listing", thoughtful: "A thoughtful listing", tipsTitle: "Help guests imagine the stay.", tip1: "Use bright, recent photos.", tip2: "Describe the neighborhood honestly.", tip3: "Set clear house rules and guest capacity.", tip4: "Choose a nightly price you can maintain."
  },
  host: {
    loadError: "Could not load your host dashboard", removeConfirm: "Remove “{{title}}”? This is only possible when it has no reservations.", removed: "Listing removed", removeError: "Could not remove this listing", loginTitle: "Log in to host your home", loginText: "Use the user menu to log in, then return here to create and manage your listings.", back: "Back to Flypnp", loading: "Loading your hosting workspace…", loadTitle: "We couldn't load your host dashboard", tryAgain: "Try again", eyebrow: "Host on Flypnp", heroTitle: "Turn your space into someone’s favorite stay.", heroText: "Create polished listings, follow guest reservations and keep your hosting business in one calm workspace.", control: "You control every listing", newPlace: "List a new place", activity: "Guest activity", recent: "Recent reservations", noReservations: "No reservations yet", noReservationsText: "New guest bookings for your listings will appear here.", guests_one: "{{count}} guest", guests_other: "{{count}} guests", message: "Message guest", portfolio: "Your portfolio", listings: "Host listings", firstTitle: "Your first listing starts here", firstText: "Add the details, photos and nightly price for the home you want travelers to discover.", published: "Published", perNight: "/ night", upTo_one: "Up to {{count}} guest", upTo_other: "Up to {{count}} guests", edit: "Edit", view: "View", removing: "Removing…", remove: "Remove", stats: { listings: "Your listings", stays: "Upcoming stays", value: "Confirmed booking value", overview: "Host overview" }
  }
} as const;

export default places;
