name: React TypeScript CI/CD

on:
  push:
    paths:
      - 'client/**'
  pull_request:
    paths:
      - 'client/**'

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache-dependency-path: backend/package-lock.json
        cache: 'npm'

    - name: Install dependencies
      run: |
        cd client
        npm ci

    - name: Run linter
      run: |
        cd client
        npm run lint

    - name: Build
      run: |
        cd client
        npm run build

    # Optional: run tests
    # - name: Run tests
    #   run: |
    #     cd client
    #     npm test
