name: React TypeScript CI/CD

on:
  push:
    paths:
      - 'client/**'
  pull_request:
    paths:
      - 'client/**'

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: client/package-lock.json

      #this is the step that installs the dependencies
    - name: Install dependencies
      run: |
        cd client
        npm ci
